# Extract variables from ServiceNow payload sr_data
oracle_host: "{{ sr_data['ITDORAHOST'] | default('not_found') }}"
oracle_port: "{{ sr_data['ITDORAPORT'] | default('1521') }}"
oracle_service: "{{ sr_data['ITDORASID'] | default('not_found') }}"
oracle_user: "{{ sr_data['ITDORAUSER'] | default('not_found') }}"
oracle_password: "{{ sr_data['ITDORAPASS'] | default('not_found') }}"

flow_id: "{{ sr_data['Classification'] | default('ITDRESORA001') }}"
expected_start: "{{ sr_data['ExpectedStart'] | default('now') }}"
oracle_container_name: "{{ sr_data['ORACLE_CONTAINER'] | default('oracle-db') }}"

