---
# Default SQL queries (can be overridden)
sql_queries:
  - name: DB Version
    query: "SELECT banner FROM v$version"

  - name: Tablespaces
    query: "SELECT tablespace_name FROM dba_tablespaces"

# Oracle connection defaults
oracle_user: ""
oracle_password: ""
oracle_service: ""

# Docker defaults
oracle_container_name: "oracle-xe"

# Results holder
sql_results: []


