---
# Default values                         # YAML start â€” this file defines default variables for the role

sql_queries:
  - name: DB Version
    query: "SELECT banner FROM v$version"

  - name: Tablespaces
    query: "SELECT tablespace_name FROM dba_tablespaces"           # The default SQL query to run if none is provide                                          # Here it returns the current Oracle database date/time.

oracle_host: ""                           # Oracle database hostname or IP. Must be supplied from SRA/SNOW input.
oracle_port: "1521"                      # Default Oracle Listener port (1521). Can be overridden.
oracle_service: ""                        # Oracle Service Name or SID (e.g., ORCL). Required for DB connection.

oracle_user: ""                           # Oracle username for authentication.
oracle_password: ""                       # Oracle password. (Can be replaced by AAP credential store.)

# ServiceNow Callback (optional, if needed)
sn_callback_url: ""                       # If your flow supports callback -> SNOW REST API endpoint.
ritm_number: ""                           # The RITM number so CACF can attach or return results to the right request.
